### ISSUE TITLE
We're not number one in Google for buy.nsw

### ISSUE THREAD

**Issue by mlandauer** [digitalnsw/buy-nsw#207]
This is confusing for users. Witnessed in user research session.

![image](https://user-images.githubusercontent.com/2221/41136570-2c4d409a-6b1a-11e8-8bba-d6c9c6f50c97.png)

**Comment by bmon** [comment]
Looks to be resolved
![image](https://user-images.githubusercontent.com/2115272/45602483-8f632180-ba62-11e8-8556-4f60eab97bb3.png)
