### ISSUE TITLE
Rename "ops" to "admin"

### ISSUE THREAD

**Issue by mlandauer** [digitalnsw/buy-nsw#36]
There is potential confusion between how `ops` is used currently in the app and the `Trailblazer::Operation`. So, let's rename `ops` to `admin` but let's leave all the `/ops` routes intact as we don't want to expose an 'admin' concept to users.

See https://ictpt.slack.com/archives/C9RMYGJ6S/p1523850242000216 for slack conversation.

**Comment by JordanHatch** [comment]
This is now complete! 🎉
