### ISSUE TITLE
Marketplace: Individual seller profile has too many redirects

### ISSUE THREAD

**Issue by devraj** [digitalnsw/buy-nsw#361]
Steps to reproduce:
- Navigate to https://marketplace.service.gov.au/search/sellers
- Click on a profile

Assumptions:
- I was logged in with my account

Environment:
- Browser: Safari 11.1.2
- OS: macOS 10.13.6

**Comment by bmon** [comment]
Hey Raj, thanks for opening this issue.

Unfortunately https://marketplace.service.gov.au is a federal project and is not part of the buy-nsw application. I'm not sure if that project is open source, but the best place to lodge issues appears to be https://marketplace1.zendesk.com/hc/en-gb/requests/new

Thanks again,
Brendan.

**Comment by bmon** [comment]
Looks like the project is open sourced, https://github.com/AusDTO/dto-digitalmarketplace-frontend could be a good place to raise this issue also.
